In [1]:
import torch

In [2]:
x=torch.zeros(5,3)

In [3]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x=x.new_ones(5,3,dtype=torch.double)

In [5]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
tensor([[ 1.6040, -0.6769,  0.0555],
        [ 0.6273,  0.7683, -0.2838],
        [-0.7159, -0.5566, -0.2020],
        [ 0.6266,  0.3566,  1.4497],
        [-0.8092, -0.6741,  0.0406]])

NameError: name 'tensor' is not defined

In [8]:
x = torch.randn(1)
print(x)
print(x.item())    #item()取出来值 我去  正常输出还有格式

tensor([0.7356])
0.7355619668960571


In [9]:
print(x.numpy())

[0.73556197]


In [10]:
x.add_(2)
print(x)

tensor([2.7356])


In [11]:
import numpy as np

In [12]:
a=np.ones(5)

In [13]:
b=torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
# Autograd

In [29]:
import torch

In [30]:
x = torch.ones(2, 2, requires_grad=True)
print(x)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [31]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [32]:
print(y.grad_fn)

In [33]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [34]:
a=torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
b=a*a*a
print(a.requires_grad)
print(b.grad_fn)

False
True


In [38]:
out.backward()
print(x.grad)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [39]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 838.2456, 1259.1715, 1225.6305], grad_fn=<MulBackward0>)


In [41]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [42]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)


True
True
False


In [44]:
abc=torch.randn(10,requires_grad=True)

In [47]:
print(abc.grad_fn)
print(abc)

None
tensor([ 0.0029,  0.4203, -0.8902,  0.2323, -0.5481,  0.2175, -0.4076, -1.6406,
        -0.4815, -0.6902], requires_grad=True)


In [48]:
z=abc*abc*4

In [49]:
print(abc.grad_fn)

None


In [51]:
z.backward(torch.rand(10))

In [52]:
print(z)

tensor([3.2992e-05, 7.0651e-01, 3.1702e+00, 2.1580e-01, 1.2017e+00, 1.8920e-01,
        6.6462e-01, 1.0766e+01, 9.2733e-01, 1.9052e+00],
       grad_fn=<MulBackward0>)


In [53]:
print(abc.grad)

tensor([ 0.0180,  1.1413, -4.1837,  1.1724, -1.5758,  1.2877, -1.5598, -6.4770,
        -1.8830, -4.0444])


In [54]:
#神经网络

In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


In [3]:
device=("cuda" if torch.cuda.is_available() else "maps" if torch.backends.mps.is_available() else "cpu")
print(device)

cuda


In [21]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.Lin=nn.Sequential(
            nn.Flatten(),
            nn.Linear(28*28,512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10),
            nn.Softmax(dim=1)
        )
        
    def forward(self,x):
 
        logits=self.Lin(x)
        return logits

In [22]:
model=Net().to(device)
print(model)

Net(
  (Lin): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=784, out_features=512, bias=True)
    (2): ReLU()
    (3): Linear(in_features=512, out_features=512, bias=True)
    (4): ReLU()
    (5): Linear(in_features=512, out_features=10, bias=True)
    (6): Softmax(dim=None)
  )
)


In [24]:
X=torch.rand(1,28,28,device=device)
logits=model(X)
print(logits)
print(torch.argmax(logits))

tensor([[0.1036, 0.1019, 0.0889, 0.1020, 0.1175, 0.1067, 0.0922, 0.0934, 0.0971,
         0.0966]], device='cuda:0', grad_fn=<SoftmaxBackward0>)
tensor(4, device='cuda:0')


/home/zhanglangeba/anaconda3/envs/cu118py310/lib/python3.10/site-packages/torch/nn/modules/container.py:217: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


In [ ]:
images=torch.rand(3,28,28)


In [37]:

#autograd
import torch
x=torch.ones(5)
y=torch.zeros(3)
w=torch.randn(5,3,requires_grad=True)
b=torch.randn(3,requires_grad=True)
z=torch.matmul(x,w)+b
loss=torch.nn.functional.binary_cross_entropy_with_logits(y,z)
print(w)
print(z)
print(loss)

tensor([[-1.6969, -0.0031, -0.5635],
        [-1.0295, -1.4162,  0.3386],
        [-1.3212, -0.1059, -0.1153],
        [-0.3948, -0.3882, -0.8270],
        [-0.7575, -1.3559, -0.4242]], requires_grad=True)
tensor([-6.3710, -0.7889, -0.5032], grad_fn=<AddBackward0>)
tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [38]:
loss.backward()  #对于矩阵方向计算 需要向量作为参数
print(w.grad)
print(b.grad)

tensor([[-0., -0., -0.],
        [-0., -0., -0.],
        [-0., -0., -0.],
        [-0., -0., -0.],
        [-0., -0., -0.]])


AttributeError: 'Tensor' object has no attribute 'g'

In [41]:
with torch.no_grad():
    zz=torch.matmul(x,w)+b
print(zz.requires_grad)

False


In [44]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import  ToTensor
train_data=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)
test_data=datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

100%|██████████████████████████████████████████████████████████████████| 26421880/26421880 [00:04<00:00, 5626944.05it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████████████████████████████████████████████████████████████████████| 29515/29515 [00:00<00:00, 94692.84it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|████████████████████████████████████████████████████████████████████| 4422102/4422102 [00:02<00:00, 1812696.93it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|█████████████████████████████████████████████████████████████████████████| 5148/5148 [00:00<00:00, 12686414.21it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [46]:
train_dataloader=DataLoader(train_data,batch_size=64)
test_dataloader=DataLoader(test_data,batch_size=64)

In [61]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.NetWork=nn.Sequential(
            nn.Flatten(),
             nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 10),
            
        )
    def forward(self,x):
        return self.NetWork(x)

In [62]:
lr=1e-3
batch_size=64
epochs=5
model=Net()
loss_fn=nn.CrossEntropyLoss()
optimizer=torch.optim.SGD(model.parameters(),lr=lr)

In [66]:
def train_loop(model,dataloader,loss_fn,optimizer):
    size=len(dataloader.dataset)
    model.train()
    for x,y in dataloader:
        optimizer.zero_grad()
        y_pred=model(x)
        loss=loss_fn(y_pred,y)  #必须 前面是预测 后面是y
        loss.backward()
        optimizer.step()
    
        

In [ ]:
for i in range(10):
    train_loop(model,train_dataloader,loss_fn,optimizer)
    print(loss)

tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
